[project]
name = "blend-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual[syntax]>=5.0.1",
    "textual-dev>=1.7.0",
]
